# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BioMultiNet',
                'doc_host': 'https://CalmScout.github.io',
                'git_url': 'https://github.com/CalmScout/BioMultiNet',
                'lib_path': 'BioMultiNet'},
  'syms': { 'BioMultiNet.cmmd': { 'BioMultiNet.cmmd.cmmd': ('cmmd.html#cmmd', 'BioMultiNet/cmmd.py'),
                                  'BioMultiNet.cmmd.communities_detection': ('cmmd.html#communities_detection', 'BioMultiNet/cmmd.py'),
                                  'BioMultiNet.cmmd.continual_multiplex_analysis': ( 'cmmd.html#continual_multiplex_analysis',
                                                                                     'BioMultiNet/cmmd.py'),
                                  'BioMultiNet.cmmd.time_it': ('cmmd.html#time_it', 'BioMultiNet/cmmd.py')},
            'BioMultiNet.utils': { 'BioMultiNet.utils.create_and_save_random_graph': ( 'generate_data.html#create_and_save_random_graph',
                                                                                       'BioMultiNet/utils.py'),
                                   'BioMultiNet.utils.create_random_graph': ( 'generate_data.html#create_random_graph',
                                                                              'BioMultiNet/utils.py'),
                                   'BioMultiNet.utils.obfuscate_nodes': ('generate_data.html#obfuscate_nodes', 'BioMultiNet/utils.py')}}}
