# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BioMultiNet',
                'doc_host': 'https://CalmScout.github.io',
                'git_url': 'https://github.com/CalmScout/BioMultiNet',
                'lib_path': 'BioMultiNet'},
  'syms': { 'BioMultiNet.utils': { 'BioMultiNet.utils.create_random_graph': ( 'generate_data.html#create_random_graph',
                                                                              'BioMultiNet/utils.py'),
                                   'BioMultiNet.utils.obfuscate_nodes': ('generate_data.html#obfuscate_nodes', 'BioMultiNet/utils.py')}}}
